# Generated by Django 4.2.7 on 2024-01-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_mainpage_states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget', models.CharField(max_length=120)),
                ('elementType', models.CharField(max_length=120)),
                ('elementState', models.BooleanField()),
                ('elementValue', models.CharField(max_length=50)),
            ],
        ),
    ]
