# Generated by Django 4.2.7 on 2024-01-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_mainpage_states',
            name='elementState',
        ),
    ]
