# Generated by Django 4.2.7 on 2024-01-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_app_mainpage_states_elementstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_mainpage_states',
            name='elementName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='app_mainpage_states',
            name='elementType',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='app_mainpage_states',
            name='elementValue',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='app_mainpage_states',
            name='widget',
            field=models.CharField(max_length=30),
        ),
    ]
