# Generated by Django 4.2.7 on 2024-02-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_app_mainpage_states_elementname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_mainpage_states',
            name='elementType',
        ),
        migrations.RemoveField(
            model_name='app_mainpage_states',
            name='widget',
        ),
    ]
