# Generated by Django 4.2.7 on 2024-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_app_mainpage_states_elementtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_mainpage_states',
            name='elementName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='app_mainpage_states',
            name='elementValue',
            field=models.CharField(max_length=100),
        ),
    ]
